### ISSUE TITLE
DIS/ENABLE_DEPTH_TEST in screenDrawing

### ISSUE THREAD

**Issue by gennaroSenatore** [remixlab/proscene#1]
hello,

I'd like to report an issue with proscene 2.x version, 
the call to DIS/ENABLE_DEPTH_TEST (so far looked at beginScreenDrawing() in abstract scene) is causing issues for the order in which lines and points are drawn in 2D. This issue might be the same reason why lines and points are also drawn not correctly in 3D when the camera eye looks at the Z axis (global)  and the lines and points are drawn in the plane xy (global)

regards

**Comment by nakednous** [comment]
@gennaroSenatore maybe `PApplet.DISABLE_OPTIMIZED_STROKE` fixes it in Proscene3?

**Comment by nakednous** [comment]
no more user input on this one so closing it
