### ISSUE TITLE
Cannot Import ik Solver

### ISSUE THREAD

**Issue by HorusMaster** [remixlab/proscene#16]
Hello when I install the library im trying to see the example of IK but i get the error: The import remixlab.dandelion.ok cannot be resolved, I manually copied and pasted the folder from the master to the sketch library remixlab dandelion folder but still is not working. Is there any indication to install the IK feature?
Best Regards Jose

**Comment by nakednous** [comment]
Inverse Kinematics is currently being developed by @sechaparroc. Install the library from the zip (which I added temporally [here](https://github.com/remixlab/proscene/blob/master/distribution/proscene-32/download/)) to test the new functionality. See also [these examples](https://github.com/remixlab/proscene/tree/master/testing/src/ik). Feedback from all backgrounds are more than welcome, so please please don't hesitate to ask any questions.

**Comment by HorusMaster** [comment]
Hello Jean Pierre, thanks for your help, ill test it and we are in touch.

Thank you!

2017-11-03 15:12 GMT-06:00 Jean Pierre Charalambos <notifications@github.com
