### ISSUE TITLE
allow rendering into an arbitrary pgraphics

### ISSUE THREAD

**Issue by nakednous** [remixlab/proscene#2]
Each `scene` has a `pgraphics` instance through which Proscene sets processing matrices at the beginning of the rendering loop. That `pgraphics` instance may be a reference either to the papplet's own main  `pgraphics` rendering context or to an external one. In this way one can easily handle both, _on-screen_ and _off-screen_ scenes. Note that in both cases the geometry is defined/handle _externally_ from within the sketch itself. So far, so good.

However, allowing to render geometry into an _arbitrary_ `pgraphics` (different than those above) may allow to easily implement [precise picking](http://n.clavaud.free.fr/processing/picking/pickcode.htm) and (to the best of my knowledge) also shader chaining (like it's done in [ofx](https://github.com/neilmendoza/ofxPostProcessing)).

The good news is that proscene already has in place all what's needed to easily set matrices into an arbitrary `PGraphics` (no matter the type, be it _JAVA2D_, _P2D_ or _P3D_). Handling geometry thus seems to be the only missing part.

Luckily, one possible simple approach to render geometry into different contexts at the moment it's needed, would be to define a collection of high-level scene `pshape` wraps which can then easily be controled by proscene means, such as when tracking `iFrames`. A basic implementation of that idea is found at the [Model development branch](https://github.com/remixlab/proscene/tree/Model) and it comprises the following main elements:
1. The `PShape` wrapper is defined in the new `Model` interface. Note that `Models` are picked by first rendering them into an `scene.pickingBuffer()`.
2. The `Model` interface has two implementations:
   1. The `InteractiveModelFrame` which is a specialization of an `InteractiveFrame` and thus exhibits a similar "interactive" behavior; and,
   2. The abstract `ModelObject` which provides a default basic implementation of that interface, as the basis to implement custom interaction behaviors.
3. While the new `scene.drawModels()` will draw all models into the main scene `pgraphics` instance, the new `scene.drawModels(PGraphics pg)` will render them into the arbritrary provided one.

The purpose of this issue is to discuss/test/improve the idea behind `Models`, gathering feedback from users which may possibly be interested in it, like @codeanticode, @eduardoMoriana, @AmnonOwed, @gennaroSenatore, @ivancastel, @merkkien, @wiarodriguezmo, @sechaparroc. Please refer to the examples found [here](https://github.com/remixlab/proscene/tree/Model/examples/Model). Note that the examples are packaged into a temporarly available library binary [here](https://github.com/remixlab/proscene/blob/Model/distribution/proscene-23/download/proscene.zip).

**Comment by edumo** [comment]
Hi 

today I've been starting a class Manager like done in ofx

Here is the code, done in eclipse :/

https://github.com/edumo/P5PostProcessing/tree/master/P5PostProcessingManager/src/main

problems:
- dependencies in the example creating Scene, Pgraphics and PostP5Manager
- better names in classes and methods
- the solution for depth is correct ?
- improvements ...
