### ISSUE TITLE
disable scene mouse tracking

### ISSUE THREAD

**Issue by Diex** [remixlab/proscene#5]
trying to disable mouse control over scene:

what I did in previous versions:
world.currentCameraProfile().removeCameraMouseBinding(PApplet.LEFT);  
world.currentCameraProfile().setFrameMouseBinding(PApplet.LEFT, MouseAction.TRANSLATE);  
world.currentCameraProfile().setClickBinding(PApplet.LEFT, 2, ClickAction.SHOW_ALL);        // 

este lo tengo que agregar

now.. (2.0.5)

world.disableMotionAgent();   // it works,

world.motionAgent().disableTracking();   // it does not.

**Comment by Diex** [comment]
also fails in 3.0

**Comment by nakednous** [comment]
`disableMotionAgent` and `disableTracking` do different things: while the former disables the agent altogether, the latter only disables tracking on the agent not allowing picking.
