### ISSUE TITLE
interactiveFrame hints remains after null

### ISSUE THREAD

**Issue by Diex** [remixlab/proscene#7]
when doing:

`iFrame = null;`

iframeHints remains on screen (actually you can still interact with it).

frame is contructed as follows (in a subclass)

```
super(scn);
setPosition(pos.x, pos.y, pos.z);
```

and:

`scene.setPickingVisualHint(true);`

**Comment by Diex** [comment]
any thoughts? maybe not an issue. is there any mechanism ala Flash:

`scene.removeChild(iframe);`

**Comment by nakednous** [comment]
to avoid a 'dangling' frame use: [scene.pruneBranch(gFrame)](http://remixlab.github.io/proscene-javadocs/remixlab/dandelion/core/AbstractScene.html#pruneBranch-remixlab.dandelion.core.GenericFrame-)
